name: "Setup Node.js and Install Dependencies"
description: "Checks out the code, sets up Node.js, and installs dependencies using npm"
runs:
  using: "composite"
  steps:
    - name: Setup npm
      uses: npm/action-setup@v4

    - name: Install dependencies
      shell: bash
      run: npm ci
