name: 'Setup Node.js and Install Dependencies'
description: 'Checks out the code, sets up Node.js, and installs dependencies using bun install --frozen-lockfile'
runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
