name: 'Setup Node.js and Install Dependencies'
description: 'Checks out the code, sets up Node.js, and installs dependencies using pnpm'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts

    - name: Generate Prisma Client (types only)
      shell: bash
      run: pnpm exec svelte-kit sync && pnpm exec prisma generate
