name: 'Setup Node.js and Install Dependencies'
description: 'Checks out the code, sets up Node.js, and installs dependencies using pnpm'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
